app:
    resource: '@AppBundle/Controller/'
    type: annotation


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
 
    

my_app_mail_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }
my_app_mail_accuse:
    path: /success
    defaults: { _controller: AppBundle:Default:success }


api_rest:
    type:     rest
    resource: "AppBundle\Controller\DefaultController"
    prefix: /api
    methods:  [GET, POST, OPTIONS]
